In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]])
print(np.tile(a, (2,1)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [4]:
a.T

array([[1., 1.]])

<function ndarray.sum>

In [21]:
b=np.array([[1,2],[3,4],[5,6]])
a.reshape(b.shape)

array([[1, 2],
       [3, 4],
       [5, 6]])

<built-in method sum of numpy.ndarray object at 0x10b5faad0>


In [24]:
np.random.rand(2,3).std()

0.2640807146950871