In [1]:
classes = ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
for y,cls in enumerate(classes):
    print(y,cls)

0 plane
1 car
2 bird
3 cat
4 deer
5 dog
6 frog
7 horse
8 ship
9 truck


In [12]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print(a[0,1])
b = np.array([1,2,3,4])
print(b)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
[1 2 3 4]


In [10]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [20]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0,1,2],[0,1,0]]) # [0,1,2] 指定行向量的序号，[0,1,0] 指定列向量的序号

[1 4 5]


In [31]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b = np.array([0,2,0,1])
print(a[np.arange(4), b]) #每行选择一个
a[np.arange(4), b] += 10
print(a) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [33]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a>2)
print(bool_idx)
print(a[bool_idx])
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [35]:
x = np.array([1,2])
y = np.array([1.0,2.0])
z = np.array([1,2], dtype = np.int64)
print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [38]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x * y)
print(np.dot(x,y))
print(x.dot(y))

[[ 5. 12.]
 [21. 32.]]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [41]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))
print(x.T)

10
[4 6]
[3 7]
[[1 3]
 [2 4]]


In [46]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1,0,1])
y = np.empty_like(x)

for i in range(4):
    y[i,:] = x[i,:] + v
print(y)

v = np.array([1,0,1])
vv = np.tile(v,(4,1))
print(vv)
y=x+vv
print(y)
z = x +v
print(z)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [2]:
import numpy as np
x = np.arange(-2, 3)
print(x)
print(np.flatnonzero(x)) #返回非零元素的坐标

[-2 -1  0  1  2]
[0 1 3 4]


In [6]:
num_training = 50
mask = list(range(num_training))
print(mask)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [11]:
nums = range(5)    # range is a built-in function that creates a list of integers
print(nums[:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"

range(0, 4)


In [14]:
from collections import Counter

words = [
    'look', 'into', 'my', 'eyes', 'look', 'into', 'my', 'eyes',
    'the', 'eyes', 'the', 'eyes', 'the', 'eyes', 'not', 'around', 'the',
    'eyes', "don't", 'look', 'around', 'the', 'eyes', 'look', 'into',
    'my', 'eyes', "you're", 'under'
]

print(Counter(words))
#OUT
# Counter({'eyes': 8, 'the': 5, 'look': 4, 'into': 3, 'my': 3, 'around': 2, "you're": 1, "don't": 1, 'under': 1, 'not': 1})


print (Counter(words).most_common(1)[0][0])

Counter({'eyes': 8, 'the': 5, 'look': 4, 'into': 3, 'my': 3, 'around': 2, 'not': 1, "don't": 1, "you're": 1, 'under': 1})
eyes


In [16]:
x = np.array([3, 1, 2])
a=np.argsort(x)
print(a)

[1 2 0]


In [17]:
print(np.square([1,2,3]))

[1 4 9]


In [18]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [2 3 4]]
[1 2 3 2 3 4]


In [6]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,0])
print(a[range(2),b])

[2 4]


In [12]:
a=np.array([0,1,1,2,3,4,0,0])
a[a>0]=1
print(a)

[0 1 1 1 1 1 0 0]


In [15]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.random.choice(a, 3)
print(b)

[1 2 7]


In [19]:
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(np.sum(a,axis=1)))

21


In [1]:
a = np.array([[1,2,3],[4,5,6]])
print(np.max(a,axis = 1))

NameError: name 'np' is not defined

In [3]:
import tensorflow as tf
import numpy as np

A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,2,3], [4,5,6]])

tf.concat([A,B], axis=1)

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


<tf.Tensor 'concat:0' shape=(2, 6) dtype=int64>