In [2]:
import tensorflow as tf
import numpy as np

In [2]:
a = [1, 2, 3, 4, 5]
print(a[0:-1] + [3 * 4])

[1, 2, 3, 4, 12]


In [5]:
b = []
for _ in range(10):
    b.append(1)
b.extend([3,4])
print(b)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 4]


In [20]:
from_tensor = tf.constant([[1,2,3,0,0], [1,3,5,6,1]])
to_mask = tf.constant([[1,1,1,0,0], [1,1,1,1,1]])

to_mask = tf.cast(tf.reshape(to_mask, [2, 1, 5]), tf.float32)
# print(to_mask_2)
broadcast_ones = tf.ones(
      shape=[2, 5, 1], dtype=tf.float32)
mask = broadcast_ones * to_mask
init = tf.global_variables_initializer()

with tf.Session() as sess:
    # print(sess.run(to_mask))
    print(sess.run(mask))

[[[1. 1. 1. 0. 0.]
  [1. 1. 1. 0. 0.]
  [1. 1. 1. 0. 0.]
  [1. 1. 1. 0. 0.]
  [1. 1. 1. 0. 0.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
