In [1]:
import tensorflow as tf
import numpy as np
tf.__version__

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


'1.10.0'

In [5]:
print(2**3)

8


In [3]:
import tensorflow as tf
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.], [2.]])
product = tf.matmul(matrix1, matrix2)

sess = tf.Session()
result = sess.run(product)
print(result)
sess.close()

[[ 12.]]


In [1]:
from __future__ import absolute_import, division, print_function

import os
import matplotlib.pyplot as plt

import tensorflow as tf
import tensorflow.contrib.eager as tfe

tf.enable_eager_execution()

print("TensorFlow version: {}".format(tf.VERSION))
print("Eager execution: {}".format(tf.executing_eagerly()))

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  retu

TensorFlow version: 1.9.0
Eager execution: True


In [2]:
train_dataset_url = "http://download.tensorflow.org/data/iris_training.csv"

train_dataset_fp = tf.keras.utils.get_file(fname=os.path.basename(train_dataset_url),
                                           origin=train_dataset_url)

print("Local copy of the dataset file: {}".format(train_dataset_fp))

8192/2194 [================================================================================================================] - 0s 0us/step
Local copy of the dataset file: /Users/didi/.keras/datasets/iris_training.csv


In [3]:
!head -n5 {train_dataset_fp}

120,4,setosa,versicolor,virginica
6.4,2.8,5.6,2.2,2
5.0,2.3,3.3,1.0,1
4.9,2.5,4.5,1.7,2
4.9,3.1,1.5,0.1,0


In [4]:
def parse_csv(line):
  example_defaults = [[0.], [0.], [0.], [0.], [0]]  # sets field types
  parsed_line = tf.decode_csv(line, example_defaults)
  # First 4 fields are features, combine into single tensor
  features = tf.reshape(parsed_line[:-1], shape=(4,))
  # Last field is the label
  label = tf.reshape(parsed_line[-1], shape=())
  return features, label

In [7]:
a=tf.sequence_mask([1, 3, 2], 5)

Tensor("SequenceMask_3/Less:0", shape=(3, 5), dtype=bool)


In [2]:
x = [[1,3,5], [2,4,6]]
tf.transpose(x, perm=[1, 0])

<tf.Tensor 'transpose:0' shape=(3, 2) dtype=int32>

In [8]:
x = [[[1,2,3,4],[5,6,7,8],[5,6,7,8]],[[9,12,13,14],[15,16,17,18],[5,6,7,8]]]
y = tf.transpose(x, perm=[1,0,2])
print(y)

Tensor("transpose_3:0", shape=(3, 2, 4), dtype=int32)


In [2]:
mask = tf.sequence_mask([1, 3, 2], 5)
with tf.Session() as sess:
    mask = sess.run(mask)
    print(mask)

[[ True False False False False]
 [ True  True  True False False]
 [ True  True False False False]]


In [6]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
tf.concat([t1, t2], axis=1) 

<tf.Tensor 'concat_2:0' shape=(2, 6) dtype=int32>

In [1]:
import datetime

In [3]:
help(datetime.strftime)

AttributeError: module 'datetime' has no attribute 'strftime'

In [10]:
    a = np.arange(8).reshape(8, 1)
    b = np.arange(8, 16).reshape(2, 4)
    c = np.arange(16, 24).reshape(2, 4)

    print("***** embedding_lookup_test_2, params:")
    print(a)
    print(b)
    print(c)

    a = tf.Variable(a)
    b = tf.Variable(b)
    c = tf.Variable(c)

    params = [a]
    print(params)
    #t = tf.nn.embedding_lookup(params=params, ids=[2, 1, 0], partition_strategy='mod')
    t = tf.expand_dims(a, -1)
    init = tf.global_variables_initializer()
    sess = tf.Session()
    sess.run(init)
    m = sess.run(t)

    print("------- embedding_lookup_test_2, result:")
    print(m)
    print(" ")

***** embedding_lookup_test_2, params:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]]
[<tf.Variable 'Variable_9:0' shape=(8, 1) dtype=int64_ref>]
------- embedding_lookup_test_2, result:
[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]]
 


In [8]:
matrix = np.random.random([1024, 64])  # 64-dimensional embeddings
ids = np.array([0, 5, 17, 33])
print(matrix[ids])  # prints a matrix of shape [4, 64] 

[[0.46962926 0.20450335 0.01564786 0.59091577 0.82912522 0.0081668
  0.92887593 0.17499348 0.0922351  0.73608525 0.44005474 0.06685198
  0.56161092 0.92901662 0.40198285 0.32804077 0.67789357 0.78956939
  0.44444345 0.69479864 0.33943008 0.81675884 0.06082183 0.80757907
  0.41709595 0.81178141 0.24147578 0.61492595 0.85437232 0.49725906
  0.44035478 0.68799093 0.60764734 0.07734517 0.90809134 0.5288716
  0.15817706 0.02125717 0.66591162 0.9303745  0.58222995 0.37794348
  0.36564142 0.98038746 0.79043405 0.87578532 0.57667564 0.2221852
  0.54956908 0.39452531 0.3810705  0.62778231 0.8843761  0.91777646
  0.15058146 0.64236002 0.79796254 0.70739756 0.89782628 0.96998654
  0.27405994 0.93427994 0.44580961 0.52236376]
 [0.4622039  0.70881066 0.41500076 0.50283675 0.50976474 0.12762025
  0.37515758 0.1692376  0.66978855 0.71106817 0.09075077 0.36214245
  0.51954743 0.04891032 0.16993066 0.40708318 0.99753488 0.62764719
  0.43812364 0.97660023 0.47231947 0.9159066  0.6205507  0.47324665
  0.

In [2]:
    a = np.arange(8).reshape(2,2,2)
    c = np.arange(9,17).reshape(2,2,2)
    print("***** embedding_lookup_test_2, params:")
    print(a.shape)
    print(a)
    a = tf.Variable(a)
    t = tf.nn.embedding_lookup(params=a, ids=[[1,1,1],[1,1,0],[1,0,0]], partition_strategy='div')
    init = tf.global_variables_initializer()
    sess = tf.Session()
    sess.run(init)
    m = sess.run(t)
    b = tf.concat([a,c], axis=1)
    b = tf.range(10, dtype=tf.int32)
    n = sess.run(b)
    print("------- embedding_lookup_test_2, result:")
    print(m)
    print(n.shape)
    print(n)
    print(" ")

***** embedding_lookup_test_2, params:
(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
------- embedding_lookup_test_2, result:
[[[[4 5]
   [6 7]]

  [[4 5]
   [6 7]]

  [[4 5]
   [6 7]]]


 [[[4 5]
   [6 7]]

  [[4 5]
   [6 7]]

  [[0 1]
   [2 3]]]


 [[[4 5]
   [6 7]]

  [[0 1]
   [2 3]]

  [[0 1]
   [2 3]]]]
(10,)
[0 1 2 3 4 5 6 7 8 9]
 


In [27]:
mask = tf.sequence_mask([1, 3, 2], tf.reduce_sum([1, 3, 4]), tf.float32)
with tf.Session() as sess:
    mask = sess.run(mask)
    print(mask)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0.]]


In [2]:
import threading
import time

from queue import Queue

def job(l,q):
    for i in range (len(l)):
        l[i] = l[i]**2
    q.put(l)

def multithreading():
    q =Queue()
    threads = []
    data = [[1,2,3],[3,4,5],[4,4,4],[5,5,5]]
    for i in range(4):
        t = threading.Thread(target=job,args=(data[i],q))
        t.start()
        threads.append(t)
    for thread in threads:
        thread.join()
    results = []
    for _ in range(4):
        results.append(q.get())
    print(results)
multithreading()

[[1, 4, 9], [9, 16, 25], [16, 16, 16], [25, 25, 25]]


In [5]:
import time
import threading

class MyThread(threading.Thread):
    def run(self):
        for i in range(5):
            print('thread {}, @number: {}'.format(self.name, i))
            time.sleep(1)

def main():
    print("Start main threading")
    # 创建三个线程
    threads = [MyThread() for i in range(3)]
    # 启动三个线程
    for t in threads:
        t.start()

    print("End Main threading")
main()

Start main threading
thread Thread-11, @number: 0
thread Thread-12, @number: 0
thread Thread-13, @number: 0
End Main threading
thread Thread-12, @number: 1thread Thread-11, @number: 1

thread Thread-13, @number: 1
thread Thread-12, @number: 2thread Thread-11, @number: 2thread Thread-13, @number: 2


thread Thread-13, @number: 3thread Thread-12, @number: 3

thread Thread-11, @number: 3
thread Thread-12, @number: 4thread Thread-13, @number: 4thread Thread-11, @number: 4




In [3]:
a = tf.get_variable('x', shape=[1], initializer=init)

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(a))
    sess.run(tf.assgin(A,[3,4]))
    print(sess.run(a))

ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: 'Tensor("Const:0", shape=(3,), dtype=int32)'