In [1]:
import tensorflow as tf

tf.__version__

'1.10.0'

In [2]:
a = tf.constant(2)
b = tf.constant(3)
c = tf.add(a, b)

with tf.Session() as sess:
    print(sess.run(c))

5


In [4]:
a = tf.constant([2, 3], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
c = tf.multiply(a, b, name='mul')
x = tf.zeros([2, 3], tf.float64)

with tf.Session() as sess:
    print(sess.run(c))
    print(sess.run(x))

[[0 3]
 [4 9]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5, 5, 5], tf.float32)

c = a + b

with tf.Session() as sess:
    print(sess.run(c, feed_dict={a:[1, 2, 3]}))

[6. 7. 8.]
